#!/usr/bin/env python3
"""A lesson outside `lessons/{core,contrib,en}/` is a lesson nobody can find (issue #2396).

The defect this pins, found 2026-09-28 while building a query bench: three *published* lessons had been
sitting at the **root** of `lessons/` since 2026-09-08, with real frontmatter, `status: published` and a
full Problem/Root-Cause/Solution/Verification body —

    lessons/ci-test-coverage-gate.md
    lessons/ci-workflow-fail-fast-matrix.md
    lessons/import-path-verification-after-refactor.md

— and the indexer walks `lessons/{core,contrib,en}` only. So they were absent from `data/lessons.json`,
and therefore from `misakanet_search`, from the site's lesson pages, and from every agent that queries the
network. Nothing said so: they were *written*, reviewed and marked published, and the corpus total (418)
counted them out.

Worse than invisible: two gates cited one of them as an *acceptable answer*
(`scripts/eval_query_aliases.py` and `workers/search-cjk-recall.test.mjs`, both for
`装了包还是提示模块找不到`), so those lists carried an expectation that could never match — the bench that
found this had to drop the id and say why.

The rule, and why it is about *location* rather than the index
-------------------------------------------------------------
`data/lessons.json` is rebuilt by the daily job, so a gate that demanded index membership would be red for
up to a day after a legitimate lesson PR lands. The indexer's rule is the location, so the gate asserts the
location:

* every `lessons/*.md` at the root must be **declared** here as not-a-lesson, with the reason;
* no file anywhere outside `core/`, `contrib/` and `en/` may claim `status: published` **and** carry a
  title — that is the shape of a lesson, and it is the shape that goes missing;
* a declaration that no longer matches a file is an error, because a dead exemption is how a gate stops
  being one.

Measured 2026-09-28: the three files above are the entire population (`hi/`, `id/`, `ru/`, `tr/`, `vi/`,
`user-rescue/`, `verified/`, `draft/`, `drafts/`, `templates/` hold scaffolding and translations, none of
them published lessons). They were moved into `contrib/` in the same change.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

yaml = pytest.importorskip("yaml", reason="PyYAML reads the lesson frontmatter")

REPO = Path(__file__).resolve().parents[1]
LESSONS = REPO / "lessons"
PUBLISHED_DIRS = ("core", "contrib", "en")

# Root files that are deliberately not lessons. Every entry needs a reason: this list is the only thing
# standing between "the indexer ignores it" and "nobody can find it".
ROOT_NOT_LESSONS: dict[str, str] = {
    "TEMPLATE.md": "the frontmatter template — a scaffolder for new lessons, not a lesson",
    "index.md": "the corpus index (no frontmatter, generated by scripts/rebuild_lessons_index.py)",
    "LESSON_QUALITY_SCORING.md": "the scoring specification: it carries title/status frontmatter, and it "
                                 "is *about* lessons rather than being one — read by maintainers, never "
                                 "served as a lesson",
}


def frontmatter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    try:
        parsed = yaml.safe_load(text[3:end])
    except yaml.YAMLError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def looks_like_a_published_lesson(path: Path) -> str | None:
    """The lesson's title when the file claims to be a published lesson, else None."""
    data = frontmatter(path.read_text(encoding="utf-8", errors="ignore"))
    if str(data.get("status", "")).strip().lower() != "published":
        return None
    title = str(data.get("title", "")).strip()
    return title or None


def undeclared_root_files(lessons: Path = LESSONS) -> list[str]:
    return sorted(p.name for p in lessons.glob("*.md") if p.name not in ROOT_NOT_LESSONS)


def published_outside_the_published_dirs(lessons: Path = LESSONS) -> list[str]:
    found = []
    for path in sorted(lessons.rglob("*.md")):
        relative = path.relative_to(lessons)
        if relative.parts[0] in PUBLISHED_DIRS or len(relative.parts) == 1:
            continue
        title = looks_like_a_published_lesson(path)
        if title:
            found.append(f"{relative.as_posix()} ({title[:60]})")
    return found


def problems(lessons: Path = LESSONS, declared: dict[str, str] | None = None) -> list[str]:
    declared = ROOT_NOT_LESSONS if declared is None else declared
    found: list[str] = []

    for name in sorted(p.name for p in lessons.glob("*.md") if p.name not in declared):
        found.append(
            f"lessons/{name} sits at the root of `lessons/`, so the indexer (which walks "
            f"{list(PUBLISHED_DIRS)}) never sees it: it is not in data/lessons.json, not in search, and "
            "not on the site. Move it into `lessons/contrib/`, or declare it in ROOT_NOT_LESSONS with "
            "the reason it is not a lesson."
        )

    for name, reason in declared.items():
        if not (lessons / name).is_file():
            found.append(
                f"ROOT_NOT_LESSONS declares {name!r} ({reason[:40]}…) but no such file exists — a dead "
                "exemption is how this gate stops being one"
            )

    for offender in published_outside_the_published_dirs(lessons):
        found.append(
            f"{offender} claims `status: published` outside {list(PUBLISHED_DIRS)}, which is the shape "
            "that goes missing: give it a home under a published directory, or drop the publishing claim"
        )
    return found


def test_no_lesson_is_hidden_at_the_root_or_outside_the_published_dirs():
    found = problems()
    assert found == [], "\n  - ".join([""] + found)


def test_the_rule_can_fail(tmp_path: Path) -> None:
    """Both halves, on a fixture — a rule that cannot go red is not a rule."""
    lessons = tmp_path / "lessons"
    (lessons / "hi").mkdir(parents=True)
    # The defect: a published lesson at the root, and the same shape in an unpublished directory.
    (lessons / "root-lesson.md").write_text(
        "---\ntitle: Hidden at the root\nstatus: published\n---\n\n## Problem\n", encoding="utf-8")
    (lessons / "hi" / "translated.md").write_text(
        "---\ntitle: Also hidden\nstatus: published\n---\n\n## Problem\n", encoding="utf-8")
    found = problems(lessons, declared={})
    assert any("root-lesson.md" in problem and "contrib" in problem for problem in found), found
    assert any("translated.md" in problem for problem in found), found

    # A stale declaration is reported too.
    stale = problems(lessons, declared={"gone.md": "was a template"})
    assert any("gone.md" in problem and "dead exemption" in problem for problem in stale), stale

    # And the control: a declared root file plus a lesson in a published directory is clean.
    (lessons / "TEMPLATE.md").write_text("---\ndomain: meta\n---\n", encoding="utf-8")
    (lessons / "contrib").mkdir()
    (lessons / "contrib" / "real.md").write_text(
        "---\ntitle: A real lesson\nstatus: published\n---\n\n## Problem\n", encoding="utf-8")
    (lessons / "root-lesson.md").unlink()
    (lessons / "hi" / "translated.md").unlink()
    assert problems(lessons, declared={"TEMPLATE.md": "the template"}) == []
