#!/usr/bin/env python3
"""The enterprise page must keep saying what the code does — including what the code does not do.

Why this file exists: `/enterprise/` is the one page written for a reader who is deciding whether to
put MisakaNet in front of a team. The failure mode for a page like that is not being wrong on the day
it is written; it is drifting afterwards, in one direction only — the disclaimers age out, the numbers
are copied by hand, and the page ends up promising more than the implementation does. This repository
has already shipped that defect three times in one week (the README hit-rate benchmark, the
LessonReuseBench status pages, the demand board — see the 2026-09-24 handoff §19.3), so the assertions
here are positive where they can be: the page must *contain* the corrections, and the numbers it quotes
must equal the constants that own them.

Deliberately **not** a token ban on "SOC 2" / "HIPAA" / "self-host": an honest page has to be able to
say those words in order to deny them, and a gate that forbids the words forbids the honesty. What is
banned is the *affirmative* form.
"""
from __future__ import annotations

import pathlib
import re

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
PAGE = REPO / "docs" / "enterprise" / "index.html"
WORKER = REPO / "workers" / "register-proxy-sw.js"

# Entry points that must link the landing page. The site navigation (`docs/index.html`) is the
# natural third one and is deliberately not asserted yet: adding it means touching a file whose
# managed lesson-count sentences are regenerated by `scripts/sync_lesson_count.py`, so it belongs in
# a change that owns that regeneration rather than in this one. Two live entry points still beats
# the page being unreachable, which is the defect this section of the project has carried.
ENTRY_POINTS = (
    "docs/maintainer/enterprise-deployment.md",
    "packages/misakanet-setup/README.md",
)

# Affirmative claims the project cannot support. Phrased as claims, not as vocabulary.
FORBIDDEN = (
    r"\bis compliant\b",
    r"\bare compliant\b",
    r"\bcompliant with (?:SOC|ISO|HIPAA|GDPR|FedRAMP)",
    r"\bwe are certified\b",
    r"\bis certified\b",
    r"\bthird[- ]party audited\b",
    r"\bindependently (?:verified|audited|validated)\b",
    r"\bpenetration[- ]test(?:ed|ing)\b",
    r"\bmulti[- ]tenant\b",
    r"\btenant isolation\b",
    r"\bguaranteed uptime\b",
    # The acronym, but not a negation of it: "no-SLA" and "no SLA" are the honest uses, and a gate
    # that forbids them forbids the disclaimer. (Found by this gate on its first run.)
    r"(?<!no-)(?<!no )\bSLA\b",
    r"\b\d+(?:\.\d+)?%\s+uptime\b",
)


@pytest.fixture(scope="module")
def page() -> str:
    return PAGE.read_text(encoding="utf-8")


def test_the_page_exists_and_is_served_as_html_not_source():
    """`.html` and not `.md`, because misakanet.org serves `docs/` verbatim with no build step.

    A `.md` file here would be published as raw source — which is exactly how the enterprise
    material was reachable before this page existed (`/maintainer/enterprise-deployment.md`
    responds `text/markdown`), and a reviewer handed that URL sees a file, not a page.
    """
    assert PAGE.is_file(), "docs/enterprise/index.html is missing"
    assert PAGE.parent.name == "enterprise", "the page must be reachable at /enterprise/"
    assert PAGE.read_text(encoding="utf-8").lstrip().startswith("<!DOCTYPE html>")


def test_no_affirmative_compliance_or_sla_claim(page):
    hits = []
    for pattern in FORBIDDEN:
        for m in re.finditer(pattern, page, re.IGNORECASE):
            hits.append(f"{pattern} -> {page[max(0, m.start() - 60):m.end() + 40]!r}")
    assert not hits, "the enterprise page asserts something the project cannot support: " + "; ".join(hits)


def test_the_boundaries_a_reviewer_must_not_misread_are_stated(page):
    """The four corrections, each of which exists because the opposite reading is the default one.

    Stated as presence assertions on purpose: a page that quietly drops one of these is the drift
    this gate is for, and "the sentence is gone" is not detectable by banning words.
    """
    lowered = page.lower()
    required = {
        "the hosted endpoint has no self-hosted form":
            r"hosted http endpoint has no self-hosted form",
        "readers must not be told there is a read quota to negotiate":
            r"no per-day read quota",
        "the query text is what leaves the machine":
            r"query text",
        "there is no organisation-level audit export":
            r"no organisation-level quota, billing view or per-tenant event export",
        "content is indexed, not verified":
            r"indexed, not .?verified",
    }
    missing = [name for name, pattern in required.items()
               if not re.search(pattern, page, re.IGNORECASE | re.DOTALL)]
    assert not missing, f"the enterprise page no longer states: {missing}"
    assert "self-hosted form" in lowered, "sanity: the self-host wording moved"


def test_the_burst_numbers_are_read_from_the_worker_not_copied(page):
    """The one number on the page that a reader will quote. It must come from its owner.

    `READ_BURST_LIMIT` is an env-overridable constant with a default, so the page's claim and the
    worker's default are two places expressing one fact. Changing the default without the page is a
    contract change, and this is what makes that visible.
    """
    src = WORKER.read_text(encoding="utf-8")
    limit = re.search(r"READ_BURST_LIMIT\s*=\s*Number\([^)]*\|\|\s*(\d+)\s*\)", src)
    window = re.search(r"READ_BURST_WINDOW_SECONDS\s*=\s*(\d+)", src)
    assert limit and window, "the worker no longer declares the burst constants in the expected shape"
    limit, window = limit.group(1), window.group(1)

    # The page states it as a rate: "<limit> reads per <window> seconds".
    assert re.search(rf"\b{limit}\b[^.]{{0,80}}\breads\s+per\s+\b{window}\b\s+seconds", page), (
        f"the page does not state the burst limit as {limit} reads per {window} seconds, which is what "
        "workers/register-proxy-sw.js declares — update whichever of the two is wrong"
    )


def test_the_page_does_not_restate_counts_that_a_script_owns(page):
    """Lesson, node, domain and tool counts are maintained by their own SSOT surfaces.

    A number written here by hand would be unmanaged (`sync_lesson_count.py` only rewrites the
    sentences registered in its `SITES` table), which is how the front page ended up advertising a
    count that no longer matched the corpus.
    """
    offenders = re.findall(r"\b\d[\d,]*\+?\s+(?:indexed\s+)?(?:failure[- ]recovery\s+)?(?:lessons|nodes|domains|tools)\b",
                           page, re.IGNORECASE)
    assert not offenders, (
        f"the enterprise page hardcodes counts owned elsewhere: {offenders}; link the surface instead"
    )


def test_every_relative_link_resolves():
    """`test_integration_docs_truth.py` resolves relative links in Markdown only — this page is HTML.

    So the two internal links a reviewer is most likely to click (`/privacy/`, `/terms/`) would
    otherwise be ungated, and a move of either page would leave a 404 on the review path.
    """
    page = PAGE.read_text(encoding="utf-8")
    internal = set(re.findall(r'href="(/[^"#?]*)"', page))
    assert internal, "expected the page to link the site's own pages"
    for href in sorted(internal):
        target = REPO / "docs" / href.strip("/")
        candidates = [target / "index.html", target] if href.endswith("/") else [target]
        assert any(c.is_file() for c in candidates), f"{href} does not resolve to a file under docs/"
    # Named explicitly so that removing one is a failure with a readable message rather than a
    # silently shorter set.
    for required in ("/privacy/", "/terms/"):
        assert required in internal, f"the enterprise page no longer links {required}"


def test_the_page_is_linked_from_its_entry_points():
    """A page nobody can reach is the defect this project has been carrying for weeks."""
    missing = []
    for rel in ENTRY_POINTS:
        path = REPO / rel
        assert path.is_file(), f"{rel} is missing"
        if "misakanet.org/enterprise/" not in path.read_text(encoding="utf-8"):
            missing.append(rel)
    assert not missing, (
        f"nothing links /enterprise/ from {missing} — a reviewer would have to guess the URL, which is "
        "the same discoverability gap as having no page at all"
    )


def test_the_maintainer_guide_and_the_page_agree_on_the_hard_boundary():
    """The guide is the long form and the page is the front door; they must not disagree.

    Only the one fact a reviewer is most likely to act on is cross-checked here (the absence of a
    self-hosted form), because asserting agreement on prose would pin wording rather than meaning.
    """
    guide = (REPO / "docs/maintainer/enterprise-deployment.md").read_text(encoding="utf-8")
    assert re.search(r"不提供自托管", guide), (
        "docs/maintainer/enterprise-deployment.md no longer states that the hosted endpoint has no "
        "self-hosted form — if that changed, the enterprise page is now the wrong one"
    )
