#!/usr/bin/env python3
"""Land an automated change on `main` through a pull request that merges itself.

Why this exists (2026-09-23)
----------------------------
`main` carries the ruleset **"main: the deterministic gates"** (id 23826057): three required
status checks — `DCO / Signed-off-by`, `test (ubuntu-latest, 3.11)`, `gate` — with
`bypass_actors: []`. GitHub evaluates those checks on the *commit being pushed*, including for a
direct push, and no actor is exempt. A push that arrives without them is refused:

    remote: error: GH013: Repository rule violations found for refs/heads/main.
    remote: - 3 of 3 required status checks are expected.
     ! [remote rejected] main -> main (push declined due to repository rule violations)

That is not hypothetical. The rule took effect on 2026-09-22 (created 21:51 +08:00, updated
23:27 +08:00) and the mirror jobs that write data into the repository started dying at their
`git push` step on their next real change: `Build Live Feed` run 35820175013 (2026-09-22 17:03
UTC) and `Mirror Node Counter` run 35843302110 (2026-09-23 09:30 UTC), each after the read and
regenerate steps had *succeeded*. Both jobs keep exiting 0 on the runs where nothing changed,
which is why the failure only appears on the days there is something to land — the exact
"the fix ran and its result was dropped" shape this repository keeps finding.

The fix is not to weaken the rule (it is what makes a green check mean something) and not to add
a bypass actor (that would exempt the bots from the very checks the rule exists for). It is to
put the automation on the path every other writer uses: a branch, a pull request, the required
checks, and a merge. This script is that path, in one place instead of eight copies.

The one property that makes it usable for a job that runs daily
--------------------------------------------------------------
A pull request that waits for a human is *worse* than the direct push it replaced: the daily jobs
would pile one unmerged PR per day in front of the maintainer, and the data would freeze exactly
as it does now. So this script does not stop at `gh pr create` — it enables **GitHub's own
auto-merge** on the PR it just opened. Once the three required checks report green, GitHub
squashes the PR into `main` with no human in the loop. A human is needed only when something is
genuinely wrong, which is what the loud failure at the end is for.

Two more decisions worth stating, because both were measured rather than assumed:

* **The branch name is stable per workflow** (`bot/<job>`), not unique per run. A second run
  force-pushes onto the same branch, so the open PR updates in place instead of a second PR
  appearing next to it. A daily job must not be able to grow a queue.
* **`GH_TOKEN` must be a PAT (`secrets.SHELDON_PAT`), never `GITHUB_TOKEN`.** A branch pushed or
  a PR opened with `GITHUB_TOKEN` starts **no** workflow runs, so the required checks never
  report and auto-merge waits forever. The repository has paid for this lesson three times
  (`.github/workflows/auto-merge-docs.yml` documents the third); it is repeated here because the
  failure mode is a PR that looks fine and never moves.

The commit message never carries a `[skip ci]` marker. That marker suppresses the *pull request's*
own runs, so the required checks would not report and the PR could never merge — a title that
contains one is refused below rather than silently stripped.

Usage (workflow):

    python3 scripts/ci/land_change.py \
      --branch bot/update-lessons \
      --title "chore: auto-update lessons.json, public counts and generated pages" \
      --note "Regenerated by .github/workflows/update-lessons.yml"

Usage (by hand, to replay what a run did):

    GH_TOKEN=$(...) python3 scripts/ci/land_change.py --branch bot/x --title "..." --dry-run

Proven live before it was given to any workflow. On 2026-09-23, from a scratch clone and with the
maintainer's PAT: **#2104** — opened 11:05Z, auto-merge enabled by this script, merged by GitHub at
11:09:56Z once the three required checks were green — and **#2105** — a second run reusing that same
branch after its pull request had been merged, which is the property every daily job depends on.
The write-up is `docs/maintainer/automation-lands-via-pr.md`; the half that keeps a workflow from
quietly going back to pushing `main` is `tests/test_no_workflow_pushes_to_main.py`.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

REPO_ROOT = Path(__file__).resolve().parents[2]
API_ROOT = "https://api.github.com"

MARKER = "<!-- misakanet-land -->"
MERGE_METHOD = "SQUASH"
COMMIT_NAME = "misakanet-bot"
COMMIT_EMAIL = "bot@misakanet.dev"

# A branch this script is allowed to write. `bot/` keeps the automation's branches recognisable in
# the branch list, and the character class keeps a workflow's name from becoming a path.
BRANCH_RE = re.compile(r"^bot/[a-z0-9][a-z0-9._-]*$")

# GitHub honours these in a commit message *or a pull request title* to suppress the runs the
# change would start. Any of them in the title would stop the required checks from reporting, so
# auto-merge would never fire.
SKIP_CI_RE = re.compile(r"\[(skip[ _-]?ci|ci[ _-]?skip|no[ _-]?ci|skip[ _-]?actions)\]", re.I)


class LandError(RuntimeError):
    """A precondition or an API call that must stop the run."""


# ────────────────────────────── pure helpers (unit-tested) ──────────────────────────────


def check_branch(branch: str) -> str:
    """Return the branch name, or refuse one this script must not push to."""
    if not BRANCH_RE.match(branch or ""):
        raise LandError(
            f"refusing to land on branch {branch!r}: expected `bot/<name>` "
            "(letters, digits, dot, underscore, dash)"
        )
    return branch


def check_title(title: str) -> str:
    """Return the title, or refuse one whose skip marker would suppress the required checks."""
    title = " ".join((title or "").split())
    if not title:
        raise LandError("a title is required: it becomes the commit subject and the PR title")
    found = SKIP_CI_RE.search(title)
    if found:
        raise LandError(
            f"the title contains {found.group(0)!r}, which tells GitHub to skip the runs this "
            "change starts — including the pull request's own required checks, so auto-merge "
            "would never fire. Drop the marker: a merge from this script triggers the push "
            "workflows (site rebuild, mirrors) on purpose."
        )
    return title


def porcelain_paths(porcelain: str) -> list[str]:
    """The paths named by `git status --porcelain` output.

    Renames are reported as `R  old -> new`; both sides are kept so `git add` stages the deletion
    as well as the addition (a rename staged by new path alone leaves the old file deleted in the
    working tree and unstaged). Paths git quotes (non-ASCII) are unquoted.
    """
    paths: list[str] = []
    for line in porcelain.splitlines():
        if len(line) < 4:
            continue
        entry = line[3:]
        if " -> " in entry:
            old, new = entry.split(" -> ", 1)
            paths += [unquote_path(old), unquote_path(new)]
        else:
            paths.append(unquote_path(entry))
    return paths


def unquote_path(path: str) -> str:
    """Undo git's C-style quoting of a path (`core.quotePath` quotes anything non-ASCII).

    The escapes are **bytes**, not characters: `caf\\303\\251.md` is `café.md` in UTF-8, so the
    escapes have to be collected as bytes and decoded once at the end. `chr()`-ing each one and
    calling it a day produces `cafÃ©.md` — a path that exists nowhere, which a later `git add`
    would report as a missing file on exactly the localized lessons this repository has.
    """
    path = path.strip()
    if not (len(path) >= 2 and path[0] == '"' and path[-1] == '"'):
        return path
    simple = {"n": "\n", "t": "\t", "r": "\r", "a": "\a", "b": "\b", "f": "\f", "v": "\v",
              "\\": "\\", '"': '"'}
    out = bytearray()
    inner, i = path[1:-1], 0
    while i < len(inner):
        ch = inner[i]
        if ch == "\\" and i + 1 < len(inner):
            octal = inner[i + 1:i + 4]
            if len(octal) == 3 and all(c in "01234567" for c in octal):
                out.append(int(octal, 8))
                i += 4
                continue
            if inner[i + 1] in simple:
                out.extend(simple[inner[i + 1]].encode())
                i += 2
                continue
        out.extend(ch.encode("utf-8"))
        i += 1
    return out.decode("utf-8", errors="replace")


def build_body(*, branch: str, title: str, files: list[str], stat: str, note: str = "",
               run_url: str = "") -> str:
    """The pull request body: one marker, what changed, and what happens next."""
    lines = [MARKER, f"### {title}", ""]
    lines += [
        "Opened by `scripts/ci/land_change.py` because `main` requires "
        "`DCO / Signed-off-by`, `test (ubuntu-latest, 3.11)` and `gate` on every commit that "
        "lands there — a direct push from the workflow that produced this change is refused by "
        "the ruleset (`3 of 3 required status checks are expected`).",
        "",
        f"**Auto-merge is enabled (squash):** GitHub merges this as soon as the three required "
        f"checks are green. Nobody has to be here for it. The branch `{branch}` is reused by the "
        "next run of this job, which force-pushes onto it and updates this pull request rather "
        "than opening a second one.",
        "",
    ]
    if run_url:
        lines += [f"**Produced by:** {run_url}", ""]
    if note:
        lines += [note.strip(), ""]
    if files:
        lines += ["**Files in this change**", ""]
        lines += [f"- `{f}`" for f in files[:40]]
        if len(files) > 40:
            lines += [f"- … and {len(files) - 40} more"]
        lines += [""]
    if stat:
        lines += ["```", stat.strip(), "```", ""]
    lines += [
        "---",
        "",
        "*If the required checks never appear on this pull request, it was opened (or its branch "
        "pushed) with `GITHUB_TOKEN`: such a run starts no workflows, so nothing will ever report "
        "and auto-merge cannot fire. Re-run the job with `secrets.SHELDON_PAT`.*",
    ]
    return "\n".join(lines) + "\n"


def auto_merge_result_ok(payload: dict) -> tuple[bool, str]:
    """Interpret a GraphQL `enablePullRequestAutoMerge` response.

    GitHub answers HTTP 200 with an `errors` array for the two states that are not failures for
    us: the PR is already set to auto-merge (a second run of the same job), and the PR is already
    merged (a scheduled job racing its own previous PR). Both mean "the change will land", which
    is what the caller needs to know.
    """
    errors = payload.get("errors") or []
    if not errors:
        return True, "auto-merge enabled"
    message = " ".join(str(e.get("message", "")) for e in errors)
    if "already enabled" in message.lower():
        return True, "auto-merge was already enabled"
    low = message.lower()
    if "already been merged" in low or ("merged" in low and "cannot" in low):
        return True, "the pull request is already merged"
    return False, message


# ────────────────────────────── side effects (integration-tested) ──────────────────────────────


class Land:
    def __init__(self, repo: str, token: str, *, cwd: Path | None = None):
        self.repo = repo
        self.token = token
        # Read at call time, not at import time, so a test can point it at a scratch repository.
        self.cwd = cwd or REPO_ROOT

    # ── git ──────────────────────────────────────────────────────────────────────────────
    def git(self, *args: str) -> str:
        """Run git in the checkout and fail loudly with its own output if it refuses."""
        proc = subprocess.run(
            ["git", *args], cwd=self.cwd, capture_output=True, text=True
        )
        if proc.returncode != 0:
            raise LandError(
                f"`git {' '.join(args)}` failed (exit {proc.returncode}):\n"
                f"{proc.stdout.strip()}\n{proc.stderr.strip()}"
            )
        return proc.stdout

    def head_is(self, base: str) -> tuple[bool, str, str]:
        """(HEAD == origin/<base>, HEAD sha, origin/<base> sha).

        The branch this job pushes becomes a pull request against `base`, and it is pushed as `HEAD` — so if
        something earlier in the workflow moved the checkout, the pull request carries *that* branch's commits
        too. Measured 2026-09-25: `release-please.yml`'s release-PR update left the workspace on
        `release-please--branches--main`, and the job that lands the version sync pushed three commits — the
        release commit, the changelog repair, and its own docs change — to `bot/release-version-sync`. The
        resulting PR was titled "docs: sync version to v2.34.0" and carried the entire **2.35.0 version bump**
        (`.release-please-manifest.json`, `pyproject.toml`, the worker's `MCP_VERSION`, `server.json`,
        `CHANGELOG.md`), which the shape guard then flagged. Landing is a statement about the generated files,
        not about whatever branch the checkout happens to be on.
        """
        head = self.git("rev-parse", "HEAD").strip()
        try:
            base_sha = self.git("rev-parse", f"origin/{base}").strip()
        except LandError:
            # A shallow or single-branch checkout may not have the remote ref. That is not a mismatch — but
            # saying nothing would disable a safety net silently, which is the shape of failure this guard
            # exists to catch, so the caller is told and the workflow can fix its checkout.
            print(
                f"::warning::origin/{base} is not in this checkout, so the \"is HEAD on the base branch\" "
                "check cannot run. `actions/checkout` with `fetch-depth: 0` (or a fetch of the base ref) "
                "restores it."
            )
            return True, head, ""
        return head == base_sha, head, base_sha

    def status_porcelain(self) -> str:
        return self.git("status", "--porcelain")

    def changed_files(self) -> list[str]:
        return porcelain_paths(self.status_porcelain())

    def stage(self, paths: list[str]) -> None:
        if paths:
            self.git("add", "--", *paths)
        else:
            self.git("add", "-A")

    def commit(self, title: str) -> str:
        self.git(
            "-c", f"user.name={COMMIT_NAME}", "-c", f"user.email={COMMIT_EMAIL}",
            "commit", "--signoff", "-m", title,
        )
        return self.git("rev-parse", "HEAD").strip()

    def diffstat(self) -> str:
        return self.git("diff", "--cached", "--stat", "HEAD").strip()

    def push(self, branch: str) -> None:
        """Publish HEAD on `branch`, replacing whatever the previous run left there.

        `--force` rather than `--force-with-lease`: the branch belongs to this job alone, and a
        lease would compare against a stale remote-tracking ref in a fresh checkout, refusing the
        push for a reason that has nothing to do with the change. Serialised by each workflow's
        `concurrency:` group.
        """
        url = f"https://x-access-token:{self.token}@github.com/{self.repo}.git"
        self.git("push", "--force", url, f"HEAD:refs/heads/{branch}")

    # ── API ──────────────────────────────────────────────────────────────────────────────
    def request(self, method: str, path: str, payload: dict | None = None) -> dict:
        url = path if path.startswith("http") else f"{API_ROOT}{path}"
        body = json.dumps(payload).encode() if payload is not None else None
        req = Request(url, data=body, method=method)
        req.add_header("Authorization", f"token {self.token}")
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("User-Agent", "misakanet-land-change")
        if body:
            req.add_header("Content-Type", "application/json")
        try:
            with urlopen(req) as resp:
                raw = resp.read().decode()
        except HTTPError as e:
            detail = e.read().decode(errors="replace")[:400]
            raise LandError(f"{method} {path} -> HTTP {e.code}: {detail}") from None
        except URLError as e:
            raise LandError(f"{method} {path} -> {e.reason}") from None
        return json.loads(raw) if raw.strip() else {}

    def open_pr(self, branch: str) -> dict | None:
        owner = self.repo.split("/")[0]
        prs = self.request("GET", f"/repos/{self.repo}/pulls?state=open&head={owner}:{branch}")
        return prs[0] if prs else None

    def create_pr(self, *, branch: str, base: str, title: str, body: str) -> dict:
        return self.request(
            "POST", f"/repos/{self.repo}/pulls",
            {"title": title, "head": branch, "base": base, "body": body},
        )

    def update_pr(self, number: int, *, title: str, body: str) -> dict:
        return self.request(
            "PATCH", f"/repos/{self.repo}/pulls/{number}", {"title": title, "body": body}
        )

    def enable_auto_merge(self, node_id: str) -> tuple[bool, str]:
        payload = self.request("POST", "/graphql", {
            "query": (
                "mutation($id: ID!, $method: PullRequestMergeMethod!) {"
                " enablePullRequestAutoMerge(input: {pullRequestId: $id, mergeMethod: $method})"
                " { pullRequest { number autoMergeRequest { enabledAt } } } }"
            ),
            "variables": {"id": node_id, "method": MERGE_METHOD},
        })
        return auto_merge_result_ok(payload)


def step_summary(text: str) -> None:
    path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not path:
        return
    try:
        with open(path, "a", encoding="utf-8") as fh:
            fh.write(text.rstrip() + "\n")
    except OSError:
        pass


def run_url() -> str:
    server = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    run_id = os.environ.get("GITHUB_RUN_ID", "")
    workflow = os.environ.get("GITHUB_WORKFLOW", "")
    if not (repo and run_id):
        return ""
    label = f"`{workflow}`" if workflow else "run"
    return f"{label} — {server}/{repo}/actions/runs/{run_id}"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--branch", required=True, help="bot/<name>, stable per workflow")
    p.add_argument("--title", required=True, help="commit subject and pull request title")
    p.add_argument("--paths", nargs="*", default=None,
                   help="paths to stage (default: everything the run changed)")
    p.add_argument("--note", default="", help="extra paragraph for the pull request body")
    p.add_argument("--base", default="main")
    p.add_argument("--repo", default=os.environ.get("GH_REPO") or os.environ.get("GITHUB_REPOSITORY", ""))
    p.add_argument("--dry-run", action="store_true",
                   help="print the plan; write nothing, call no API")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        branch = check_branch(args.branch)
        title = check_title(args.title)
    except LandError as e:
        print(f"::error::{e}")
        return 1

    land = Land(args.repo, os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", ""))

    # Fail loudly when the checkout is not on the branch this pull request targets. The alternative is a
    # pull request whose title describes one change and whose diff contains another (see `head_is`).
    same, head_sha, base_sha = land.head_is(args.base)
    if not same:
        print(
            f"::error::HEAD is {head_sha[:10]} but origin/{args.base} is {base_sha[:10] or 'unknown'} — the "
            f"workflow moved the checkout, so landing would push that branch's commits to `{args.branch}` "
            "as well. Restore the checkout (`git checkout --force " + args.base + "`) after whatever moved "
            "it, or land from a separate worktree."
        )
        return 1

    # No `--paths`: everything the run changed. That is what the workflows these jobs replaced did
    # (`git add -A`), and a hand-written path list is how the node-counter job once threw away the
    # README tables its own refresh step had just corrected.
    staged_now = list(args.paths) if args.paths else land.changed_files()

    if not staged_now:
        # The early exit every one of these jobs already had: a regeneration that produced an
        # identical file is not a change, and a pull request for it would be noise. Exit 0 — the
        # job's real work *was* to check, and it did.
        print("nothing to land — the generated files already match what is on main.")
        step_summary("### Nothing to land\n\nThe generated files already match `main`.")
        return 0

    print(f"landing {len(staged_now)} path(s) on {branch}: {', '.join(staged_now[:10])}"
          + (" …" if len(staged_now) > 10 else ""))

    if args.dry_run:
        print(json.dumps({"branch": branch, "title": title, "base": args.base,
                          "paths": staged_now, "dry_run": True}, indent=2, ensure_ascii=False))
        return 0

    if not land.token:
        print("::error::no GH_TOKEN/GITHUB_TOKEN in the environment — cannot open or merge a pull request")
        return 1

    try:
        land.stage(staged_now)
        stat = land.diffstat()
        if not stat:
            print("nothing to land — the staged paths are identical to HEAD.")
            step_summary("### Nothing to land\n\nThe staged paths are identical to `HEAD`.")
            return 0
        sha = land.commit(title)
        land.push(branch)
    except LandError as e:
        print(f"::error::{e}")
        return 1

    body = build_body(branch=branch, title=title, files=staged_now, stat=stat,
                      note=args.note, run_url=run_url())
    try:
        existing = land.open_pr(branch)
        if existing:
            pr = land.update_pr(existing["number"], title=title, body=body)
            action = f"updated #{pr['number']}"
        else:
            pr = land.create_pr(branch=branch, base=args.base, title=title, body=body)
            action = f"opened #{pr['number']}"
    except LandError as e:
        print(f"::error::pushed {sha[:10]} to {branch}, but the pull request was not created: {e}")
        print(f"::error::the change is on branch {branch} — open the pull request by hand.")
        return 1

    try:
        ok, why = land.enable_auto_merge(pr["node_id"])
    except LandError as e:
        ok, why = False, str(e)

    print(f"{action}: {pr['html_url']} ({why})")
    step_summary(
        f"### Landed via pull request\n\n"
        f"- **{action}** — {pr['html_url']}\n"
        f"- auto-merge (squash): {'enabled' if ok else '**NOT enabled** — ' + why}\n"
        f"- commit `{sha[:10]}` on `{branch}`\n"
    )
    if not ok:
        # Deliberately a failure: a pull request that will never merge is a silent data freeze,
        # which is the failure this whole path exists to remove.
        print(
            f"::error::PR #{pr['number']} is open but auto-merge could not be enabled ({why}). "
            "Merge it by hand, or fix the cause and re-run this job."
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
