#!/usr/bin/env python3
"""Extract the search page's scorer into a module the parity bench can `import` (no dynamic execution).

WHY (2026-09-30): `scripts/bench_search_parity.mjs` must measure **the page's own scorer**, not a
reimplementation of it — otherwise it compares a copy against the original and calls the difference drift.
The first version lifted `isSearchable`/`search` out of `docs/search/index.html` at run time and built them
by constructing and executing them at run time, which is dynamic code execution and was reported as such:

    plugin-scanner: DANGEROUS_DYNAMIC_EXECUTION (error) scripts/bench_search_parity.mjs:1  (alert #290)

Extracting at **build** time removes the execution entirely while keeping the property: this script writes
`scripts/page_scorer.mjs`, and `tests/test_page_scorer_generated.py` fails whenever the page's functions and
the committed module differ — so "the bench runs the page's scorer" is now *gated* rather than *asserted by
a mechanism a scanner is right to dislike*.

Usage:
    python3 scripts/build_page_scorer.py            # write scripts/page_scorer.mjs
    python3 scripts/build_page_scorer.py --check    # exit 1 when stale (what the test calls)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PAGE = REPO / "docs" / "search" / "index.html"
TARGET = REPO / "scripts" / "page_scorer.mjs"
FUNCTIONS = ("isSearchable", "search")

HEADER = """// GENERATED by scripts/build_page_scorer.py from docs/search/index.html — do not edit by hand.
// Regenerate: python3 scripts/build_page_scorer.py      (tests/test_page_scorer_generated.py fails when stale)
//
// Why a copy exists at all: `scripts/bench_search_parity.mjs` measures the *page's own* scorer, and the first
// version lifted these functions out of the HTML at run time and executed them — dynamic code execution,
// reported as DANGEROUS_DYNAMIC_EXECUTION (alert #290). Extracting at build time keeps the property ("same
// code as the page") and makes it checkable: the gate compares this file to the page.
export function makePageSearch(_lessons) {
"""


def function_source(html: str, name: str) -> str:
    """The function's source, brace-matched, exactly as it appears in the page."""
    start = html.find(f"function {name}(")
    if start < 0:
        raise SystemExit(f"docs/search/index.html no longer defines {name}() — the extractor must be updated")
    depth = 0
    opening = html.find("{", start)
    for index in range(opening, len(html)):
        if html[index] == "{":
            depth += 1
        elif html[index] == "}":
            depth -= 1
            if depth == 0:
                return html[start:index + 1]
    raise SystemExit(f"could not read {name}() to its closing brace")


def build(page_text: str | None = None) -> str:
    html = page_text if page_text is not None else PAGE.read_text(encoding="utf-8")
    body = "\n\n".join(function_source(html, name) for name in FUNCTIONS)
    return f"{HEADER}{body}\n\n  return {{ {', '.join(FUNCTIONS)} }};\n}}\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Extract the search page's scorer into scripts/page_scorer.mjs")
    parser.add_argument("--check", action="store_true", help="report drift without writing; exit 1 if stale")
    args = parser.parse_args(argv)

    wanted = build()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if current == wanted:
        print(f"OK {TARGET.relative_to(REPO)} matches docs/search/index.html")
        return 0
    if args.check:
        print(f"FAIL {TARGET.relative_to(REPO)} is stale — run: python3 scripts/build_page_scorer.py")
        return 1
    TARGET.write_text(wanted, encoding="utf-8")
    print(f"OK wrote {TARGET.relative_to(REPO)} ({len(wanted)} bytes) from docs/search/index.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
