// GENERATED by scripts/build_page_scorer.py from docs/search/index.html — do not edit by hand.
// Regenerate: python3 scripts/build_page_scorer.py      (tests/test_page_scorer_generated.py fails when stale)
//
// Why a copy exists at all: `scripts/bench_search_parity.mjs` measures the *page's own* scorer, and the first
// version lifted these functions out of the HTML at run time and executed them — dynamic code execution,
// reported as DANGEROUS_DYNAMIC_EXECUTION (alert #290). Extracting at build time keeps the property ("same
// code as the page") and makes it checkable: the gate compares this file to the page.
export function makePageSearch(_lessons) {
function isSearchable(l) {
  const text = ((l.title||'') + ' ' + (l.summary||'')).toLowerCase();
  const junk = ['context compaction','earlier turns','poc record','mojibake','bot reply'];
  return !junk.some(k => text.includes(k)) && (l.title||'').trim();
}

function search(q) {
  if (!q || !_lessons) return [];
  const tokens = q.toLowerCase().split(/\s+/).filter(Boolean);
  return _lessons.filter(isSearchable).map(l => {
    const title = (l.title||'').toLowerCase();
    const domain = (l.domain||'').toLowerCase();
    const summary = (l.summary||'').toLowerCase();
    const tags = (l.tags||[]).join(' ').toLowerCase();
    const full = title + ' ' + domain + ' ' + summary + ' ' + tags;
    let score = tokens.filter(t => full.includes(t)).length / tokens.length;
    if (tokens.some(t => title.includes(t))) score += 0.3;
    if (tokens.some(t => tags.includes(t))) score += 0.15;
    if (tokens.some(t => domain.includes(t))) score += 0.1;
    return { ...l, score };
  }).filter(l => l.score > 0).sort((a,b) => b.score - a.score).slice(0, 20);
}

  return { isSearchable, search };
}
